### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by raulikeda** [juanjorgegarcia/privateCloudServer#1]
ubuntu@ip-172-31-89-117:~/privateCloudServer$ ./runserver.sh 

> server@1.0.0 prod /home/ubuntu/privateCloudServer
> npm run build && npm run start

> server@1.0.0 build /home/ubuntu/privateCloudServer
> tsc

> server@1.0.0 start /home/ubuntu/privateCloudServer
> node ./dist/server.js

module.js:549
    throw err;
    ^

Error: Cannot find module './env'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/privateCloudServer/dist/app.js:8:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/privateCloudServer/dist/server.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

npm ERR! Linux 4.15.0-1051-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! server@1.0.0 start: `node ./dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 start script 'node ./dist/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./dist/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/privateCloudServer/npm-debug.log

npm ERR! Linux 4.15.0-1051-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "prod"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! server@1.0.0 prod: `npm run build && npm run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 prod script 'npm run build && npm run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/privateCloudServer/npm-debug.log

**Comment by raulikeda** [comment]
Aliás, um bom readme seria bom.
